name: Fastlane test

on: 
  push:
    branches:
      - release

jobs:
  test:
    name: Testing using fastlane
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Test
        run: fastlane test
