name: Release using fastlane

on: 
  push:
    branches:
      - release

jobs:
  test:
    name: Testing using fastlane
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      # - name: Test
      #  run: fastlane test
      
      - name: Build
        run: fastlane adhoc
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          A_2359_APP_MANAGER_API_KEY: ${{ secrets.A_2359_APP_MANAGER_API_KEY }}
