name: Fastlane test

on: 
  push:
    branches:
      - release

jobs:
  test:
    name: Testing using fastlane
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: '>= 2.6'
          
      - name: Install bundler
        run: |
          gem install bundler:1.17.2
          
      - uses: maierj/fastlane-action@v2.0.0
        with:
          lane: 'test'
