name: Release using fastlane

on: 
  push:
    branches:
      - release
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags'   

jobs:
  test:
    name: Testing using fastlane
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      # - name: Test
      #  run: fastlane test
      
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: '>= 2.6'
          
      - name: Install bundler
        run: |
          gem install bundler:1.17.2
          
      - name: Build
        uses: maierj/fastlane-action@v2.0.0
        with:
          lane: 'adhoc'
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          A_2359_APP_MANAGER_API_KEY: ${{ secrets.A_2359_APP_MANAGER_API_KEY }}
