name: On pull request

on: 
  pull_request:
    branches:
      - master
      - develop
      
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: fastlane test
          
  swiftlint:
    name: Swiftlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
