name: Fastlane test

on: 
  pull_request:
    branches:
      - master
      - develop
      - release

jobs:
  test:
    name: Testing using fastlane
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: '>= 2.6'
          
      - uses: maierj/fastlane-action@v2.0.0
        with:
          lane: 'test'
          
  swiftlint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
